use_frameworks!

platform :ios, '9.0'

target 'LEBLManager_Example' do
  pod 'LEBLManager', :path => '../'

  target 'LEBLManager_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
